[package]
name = "Executer"
version = "0.1.0"
authors = ["LiuHaolan <3140101098@zju.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
